const express = require("express");
const {register, login, getProfile, } = require("../controllers/authControler");
const {protect} = require("../middleware/authMiddleware");
const {logout, forgotPassword} = require("../controllers/authControler");
const router = express.Router();
router.post("/register", register);
router.post("/login", login);
router.get("/profile", protect, getProfile);
router.post("/logout", protect, logout);
router.post("/forgot-password", forgotPassword);
module.exports = router;
